name: Android CI

on:
  push:
    branches:
      - main
      - 'feature/*'
      - 'bugfix/*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Prepare Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools-version: '33.0.2'
          ndk-version: '25.1.8937393'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Upload Unit Test Reports
        uses: actions/upload-artifact@v3
        with:
           name: unit-test-reports
           path: app/build/reports/tests/testDebugUnitTest

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name:  Get test artifacts
        uses: actions/download-artifact@v3
        with:
          name: unit-test-reports

      - name: output contents
        run: ls
            
      
